# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

from waflib import Logs

def build(bld):
    bld(features='cxx',
        target='unit-tests-main',
        name='unit-tests-main',
        source='main.cpp',
        use='BOOST',
        includes='.. .',
        defines=['BOOST_TEST_MODULE=ChronoShare Unit Tests'])

    unit_tests = bld.program(
            target='../unit-tests',
            features='qt5 cxx cxxprogram',
            source=bld.path.ant_glob(['*.cpp',
                                      'unit-tests/sync-*.t.cpp',
                                      'unit-tests/action-log.t.cpp',
                                      'unit-tests/object-manager.t.cpp',
                                      'unit-tests/fetch*.t.cpp',
                                      'unit-tests/serve-and-fetch.t.cpp',
                                      'unit-tests/dispatcher.t.cpp',
                                      'unit-tests/fs-watcher*.t.cpp',
                                      ],
                                     excl=['main.cpp']),
            use='unit-tests-main chronoshare fs-watcher QT5CORE QT5GUI QT5WIDGETS',
            install_path=None,
            defines='UNIT_TEST_CONFIG_PATH=\"%s/tmp-files/\"' % (bld.bldnode),
            includes='.. ../src ../fs-watcher .',
          )

    Logs.error("Most unit tests are temporary disabled")
